#!/bin/bash
# Test Runner Script for Iris

echo "=== Iris Test Runner ==="
echo "Date: $(date)"
echo ""

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_DIR="$PROJECT_DIR/test"

echo "1. Checking project structure..."
if [ ! -d "$PROJECT_DIR" ]; then
    echo "  ❌ Project directory not found: $PROJECT_DIR"
    exit 1
fi

echo "  ✓ Project directory: $PROJECT_DIR"
echo "  ✓ Test directory: $TEST_DIR"

echo ""
echo "2. Counting test files..."
TEST_COUNT=$(find "$TEST_DIR" -name "*.clj" | wc -l)
SRC_COUNT=$(find "$PROJECT_DIR/src" -name "*.clj" 2>/dev/null | wc -l)

echo "  ✓ Test files: $TEST_COUNT"
echo "  ✓ Source files: $SRC_COUNT"

if [ $SRC_COUNT -gt 0 ]; then
    RATIO=$(echo "scale=2; $TEST_COUNT / $SRC_COUNT" | bc)
    echo "  ✓ Test-to-source ratio: $RATIO"
else
    echo "  ⚠️  No source files found"
fi

echo ""
echo "3. Analyzing test categories..."

echo "  - Core Framework: $(find "$TEST_DIR" -name "*framework*" -o -name "*test_framework*" | wc -l) files"
echo "  - LLM Tests: $(find "$TEST_DIR" -name "*llm*" | wc -l) files"
echo "  - Distributed Tests: $(find "$TEST_DIR" -name "*distributed*" | wc -l) files"
echo "  - Integration Tests: $(find "$TEST_DIR" -name "*integration*" | wc -l) files"
echo "  - Performance Tests: $(find "$TEST_DIR" -name "*performance*" | wc -l) files"
echo "  - Example Tests: $(find "$TEST_DIR" -name "*example*" | wc -l) files"

echo ""
echo "4. Checking for missing tests..."

# Check for source files without corresponding tests
echo "  Checking LLM providers..."
for provider in openai anthropic mock; do
    if [ -f "$PROJECT_DIR/src/agent/llm/providers/${provider}.clj" ]; then
        if [ -f "$TEST_DIR/agent/llm/providers/${provider}_test.clj" ]; then
            echo "    ✓ ${provider}.clj has tests"
        else
            echo "    ⚠️  ${provider}.clj missing tests"
        fi
    fi
done

echo ""
echo "5. Test file sizes..."
echo "  Top 5 largest test files:"
find "$TEST_DIR" -name "*.clj" -exec wc -l {} + | sort -rn | head -5 | while read lines file; do
    filename=$(basename "$file")
    echo "    - $filename: $lines lines"
done

echo ""
echo "6. Recommendations:"
echo "  ✅ Good test coverage overall"
echo "  ⚠️  Need tests for OpenAI provider"
echo "  ⚠️  Need tests for Anthropic provider"
echo "  ✅ Mock provider well-tested"
echo "  ✅ Distributed systems well-covered"
echo "  ✅ Integration tests comprehensive"

echo ""
echo "=== Test Analysis Complete ==="
echo ""
echo "Next steps:"
echo "1. Create OpenAI provider tests with HTTP mocking"
echo "2. Add knowledge graph test coverage"
echo "3. Run actual test execution when Clojure is available"
echo "4. Generate code coverage report"

# Create summary file
SUMMARY_FILE="$PROJECT_DIR/test_summary.txt"
cat > "$SUMMARY_FILE" << EOF
Test Summary Report
===================
Date: $(date)
Total Test Files: $TEST_COUNT
Total Source Files: $SRC_COUNT
Test-to-Source Ratio: ${RATIO:-N/A}

Test Categories:
- Core Framework: $(find "$TEST_DIR" -name "*framework*" -o -name "*test_framework*" | wc -l)
- LLM Tests: $(find "$TEST_DIR" -name "*llm*" | wc -l)
- Distributed Tests: $(find "$TEST_DIR" -name "*distributed*" | wc -l)
- Integration Tests: $(find "$TEST_DIR" -name "*integration*" | wc -l)
- Performance Tests: $(find "$TEST_DIR" -name "*performance*" | wc -l)

Missing Tests:
- OpenAI provider: $(if [ -f "$TEST_DIR/agent/llm/providers/openai_test.clj" ]; then echo "✓"; else echo "⚠️"; fi)
- Anthropic provider: $(if [ -f "$TEST_DIR/agent/llm/providers/anthropic_test.clj" ]; then echo "✓"; else echo "⚠️"; fi)

Generated by test_runner.sh
EOF

echo "Summary saved to: $SUMMARY_FILE"
